// Generated by the dumpyard CLI — do not hand-edit.
//
// One entry per locked folder: a salt and HMAC-SHA256(pepper, salt:password).
// Without the site's pepper (a Cloudflare secret, never in this repo) these
// hashes can't be cracked. Longest matching prefix wins, so locking
// "/project-xyz/" covers every page, note, PDF and image under it. A path
// matching nothing here is public.
export default {
};
