// Generated by the dumpyard CLI — do not hand-edit.
//
// Salted SHA-256 of each path's password. Hashes are not secrets, so this file
// lives in the repo and there is no limit on how many paths you can lock.
// Longest matching prefix wins, so locking "/project-xyz/" covers every page,
// note, PDF and image under it. A path matching nothing here is public.
export default {
};
